### PR TITLE
Download individual states

### PR DESCRIPTION
**Pull request by datalorax**
Hi Isabella,

This is a pretty major rewrite of `lea_get` so I think you'll probably want to review it pretty carefully before merging. What I ended up doing was creating a repo [here](https://github.com/datalorax/us-district-shapefiles/tree/master/individ-districts) that has the data files for each state. Then I rewrote the function so it can pull any state or combination of states. You can pass abbreviations now too. I'm pretty sure this makes `lea_prep` unnecessary. 

Happy to chat about this more! I wrote the code all in base so I didn't introduce any new dependencies, but we could make it more readable by including some, if you want (e.g., `purrr::map2` instead of `base::Map`). I also used temporary directories throughout so there's no need to specify a path anymore. I do really like the ability to do something like the following now:

```r
library(leaidr)
northwest <- lea_get(c("or", "wa"))

northwest %>% 
  sf::st_as_sf() %>% 
  ggplot2::ggplot() +
  ggplot2::geom_sf()
```
4ff9141f-40e2-42e5-b033-9433f5d798d9

And if you use `lea_get()` (i.e., with `state = NULL`) you get the whole US back via piggyback, as you had it before. 

If you use a lot of states I'm not sure how much faster this actually is. Maybe there should be a decision rule where if it's more than, say, three, you just download the whole US file and then subset it.

Also - just saw that @jrosen48 is an author on this too. Awesome!

### CODE REVIEW

**Comment by ivelasq** [comment]
Thanks so much! I will take a look this weekend :)

**Comment by datalorax** [comment]
One other option I thought about this morning is instead of keeping a GitHub repo with all the individual state files we could use OSF and then access the files with their API. I think CRAN would probably like that more, but I'm not sure. Seems a little more stable. I don't have experience with doing that but I know @jrosen48 does.

**Comment by ivelasq** [comment]
Sorry this took so long. "This month" ≈ "This weekend", right?!

Thank you so much for looking into this and more fully expanding it. Amazing! I think I will write a new blog post with the new workflow.

@jrosen48 would love your thoughts on the API!

**Comment by jrosen48** [comment]
Sorry I didn't get to this, all. I have added this to my to do (specifically the question of how we could store the data on OSF).

**Pull request merged**
